spring:
  application:
    name: userservice
  docker.compose.lifecycle-management: start_only
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/userservice
    username: haisia
    password: test@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
